INSERT INTO tb_category(name, created_at) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Electronic', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Smartphones', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Home Appliances', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Gaming', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Furniture', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Fashion', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Sports', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Toys & Games', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Beauty & Health', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Automotive', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Music', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Garden & Outdoors', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Groceries', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Watches & Accessories', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Baby Products', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Industrial & Tools', NOW());

INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('The Lord of the Rings', 90.5, 'Epic fantasy novel by J.R.R. Tolkien, journey of Frodo Baggins to destroy the One Ring.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg', '2023-08-01 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Smart TV 55', 2190.0, '4K UHD Smart TV with HDR and integrated streaming apps.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/2-big.jpg', '2023-08-23 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('MacBook Pro 14', 1250.0, 'Apple M1 Pro chip with Retina Display and long battery life.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/3-big.jpg', '2023-10-17 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Elite', 1200.0, 'High-performance gaming PC with NVIDIA GeForce and Ryzen 7.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/4-big.jpg', '2024-01-08 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Rails for Dummies', 100.99, 'Beginner guide to Ruby on Rails for web development.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/5-big.jpg', '2024-01-29 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Ex Pro', 1350.0, 'Advanced gaming desktop with RTX 3060 and SSD storage.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/6-big.jpg', '2024-02-16 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Xtreme', 1350.0, 'Gaming beast with liquid cooling and RGB lighting.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/7-big.jpg', '2024-03-02 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Alfa', 1850.0, 'High-speed performance PC for competitive gaming.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/8-big.jpg', '2024-03-18 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Tera', 1950.0, 'Heavy-duty gaming desktop with latest Intel processor.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/9-big.jpg', '2024-04-02 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Y', 1700.0, 'Sleek, powerful desktop built for 1080p gaming.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/10-big.jpg', '2024-06-05 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Nitro', 1450.0, 'Customizable gaming setup with great airflow.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/11-big.jpg', '2024-09-03 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Card', 1850.0, 'Mid-tower gaming PC with solid GPU and cooling.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/12-big.jpg', '2024-09-19 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Plus', 1350.0, 'Entry-level gaming PC for casual gamers.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/13-big.jpg', '2024-10-18 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Hera', 2250.0, 'High-end PC with premium case design and fast SSD.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/14-big.jpg', '2024-10-27 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Weed', 2200.0, 'Beast PC for streaming and VR gaming.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/15-big.jpg', '2024-11-04 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Max', 2340.0, 'Top-tier specs with powerful multitasking ability.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/16-big.jpg', '2024-11-20 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Turbo', 1280.0, 'Gaming machine with overclocking features.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/17-big.jpg', '2024-12-09 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Hot', 1450.0, 'Performance machine with excellent thermal control.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/18-big.jpg', '2025-02-18 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Ez', 1750.0, 'Easy setup gaming PC for plug-and-play.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/19-big.jpg', '2025-02-20 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Tr', 1650.0, 'Compact design with full-sized power.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/20-big.jpg', '2025-03-04 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Tx', 1680.0, 'Silent gaming PC with SSD boot drive.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/21-big.jpg', '2025-03-15 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Er', 1850.0, 'Energy-efficient setup with premium parts.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/22-big.jpg', '2025-03-28 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Min', 2250.0, 'Minimalist case with high airflow design.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/23-big.jpg', '2025-05-02 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Boo', 2350.0, 'Strong GPU and multi-monitor ready system.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/24-big.jpg', '2025-06-06 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('PC Gamer Foo', 4170.0, 'Ultimate machine for hardcore gamers and creators.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/25-big.jpg', '2025-06-17 21:47:25');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('The Art of Computer Programming', 150.0, 'Comprehensive monograph written by Donald Knuth covering many kinds of programming algorithms and their analysis.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/26-big.jpg', '2025-06-01 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Air Fryer XL', 299.0, 'Large capacity air fryer with digital controls and easy-clean basket for healthy frying.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/27-big.jpg', '2025-06-04 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Mountain Bike Pro', 1100.0, 'Durable mountain bike with 21-speed gear system and hydraulic disc brakes.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/28-big.jpg', '2025-06-07 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Acoustic Guitar', 450.0, 'Six-string acoustic guitar with mahogany top and natural finish.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/29-big.jpg', '2025-06-10 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Ergonomic Office Chair', 320.0, 'Adjustable lumbar support, mesh backrest, and 360-degree swivel design.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/30-big.jpg', '2025-06-13 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Organic Honey Jar', 20.0, 'Pure raw organic honey packed in a glass jar straight from the farm.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/31-big.jpg', '2025-06-16 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Digital Watch Series 5', 499.0, 'Stylish digital watch with GPS and heart rate tracking features.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/32-big.jpg', '2025-06-19 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Baby Stroller 3-in-1', 750.0, 'Multifunctional stroller with carrycot and car seat included.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/33-big.jpg', '2025-06-22 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Toy Construction Set', 45.0, 'Creative building block toy set with 300 pieces for ages 6+.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/34-big.jpg', '2025-06-25 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Bluetooth Headphones', 125.0, 'Wireless over-ear headphones with noise cancellation.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/35-big.jpg', '2025-06-28 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Hydraulic Car Jack', 85.0, '2-ton hydraulic jack for lifting vehicles safely.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/36-big.jpg', '2025-07-01 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Gaming Controller Pro', 90.0, 'Ergonomic controller compatible with PC, PlayStation, and Xbox.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/37-big.jpg', '2025-07-04 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Pet Bed Large', 60.0, 'Soft plush pet bed suitable for medium to large dogs.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/38-big.jpg', '2025-07-07 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Garden Hose 50ft', 35.0, 'Flexible, kink-free garden hose with spray nozzle.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/39-big.jpg', '2025-07-10 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Makeup Kit Essentials', 70.0, 'Complete beauty makeup set with brushes and mirror.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/40-big.jpg', '2025-07-13 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Smartphone X20', 999.0, 'Flagship smartphone with AMOLED display and 128GB storage.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/41-big.jpg', '2025-07-16 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Fashion Leather Wallet', 55.0, 'Men’s genuine leather wallet with RFID blocking.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/42-big.jpg', '2025-07-19 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Adjustable Dumbbell', 199.0, 'Single dumbbell with adjustable weight plates (5-52.5 lbs).', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/43-big.jpg', '2025-07-22 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Desk Organizer Set', 25.0, '5-piece office desk organizer in black metal mesh.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/44-big.jpg', '2025-07-25 10:00:00');
INSERT INTO tb_product (name, price, description, img_url, created_at) VALUES ('Cordless Drill Kit', 180.0, 'Powerful 20V cordless drill with battery and case.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/45-big.jpg', '2025-07-28 10:00:00');


INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (21, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (22, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (23, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (25, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (26, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (27, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (28, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (29, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (30, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (31, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (32, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (33, 8);
INSERT INTO tb_product_category (product_id, category_id) VALUES (34, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (35, 10);
INSERT INTO tb_product_category (product_id, category_id) VALUES (36, 11);
INSERT INTO tb_product_category (product_id, category_id) VALUES (37, 12);
INSERT INTO tb_product_category (product_id, category_id) VALUES (38, 13);
INSERT INTO tb_product_category (product_id, category_id) VALUES (39, 14);
INSERT INTO tb_product_category (product_id, category_id) VALUES (40, 15);
INSERT INTO tb_product_category (product_id, category_id) VALUES (41, 16);
INSERT INTO tb_product_category (product_id, category_id) VALUES (42, 17);
INSERT INTO tb_product_category (product_id, category_id) VALUES (43, 18);
INSERT INTO tb_product_category (product_id, category_id) VALUES (44, 19);
INSERT INTO tb_product_category (product_id, category_id) VALUES (45, 20);


INSERT INTO tb_user (first_name, last_name, email, phone, password, birth_date) VALUES ('Maria', 'Brown', 'maria@gmail.com', '988888888', '$2a$10$hekAig9V0rG/0/Svd5m6..7sl3hQmVhBwqaNmbf9zfEsj6brViBfC', '2001-07-25');
INSERT INTO tb_user (first_name, last_name, email, phone, password, birth_date) VALUES ('Alex', 'Green', 'alex@gmail.com', '977777777', '$2a$10$hekAig9V0rG/0/Svd5m6..7sl3hQmVhBwqaNmbf9zfEsj6brViBfC', '1987-12-13');

INSERT INTO tb_order (status, client_id, created_at) VALUES (1, 1, TIMESTAMP WITH TIME ZONE '2022-02-01T15:00:00Z');
INSERT INTO tb_order (status, client_id, created_at) VALUES (3, 2, TIMESTAMP WITH TIME ZONE '2022-06-15T15:00:00Z');
INSERT INTO tb_order (status, client_id, created_at) VALUES (0, 1, TIMESTAMP WITH TIME ZONE '2022-05-10T15:00:00Z');

INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (1, 1, 2, 90.5);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (1, 3, 1, 1250.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (2, 3, 1, 1250.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (3, 1, 1, 90.5);

INSERT INTO tb_payment (order_id, payment_time) VALUES (1, TIMESTAMP WITH TIME ZONE '2022-07-25T15:00:00Z');
INSERT INTO tb_payment (order_id, payment_time) VALUES (2, TIMESTAMP WITH TIME ZONE '2022-07-30T11:00:00Z');

INSERT INTO tb_role (authority) VALUES ('ROLE_CLIENT');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);